### PR TITLE
Skip child shutdown

### PR DESCRIPTION
**Pull request by garex**
When we are under php-fpm, master process goes inside startup hook once.
When our child ended/killed by some reason (max_requests for example), it visit shutdown hook.
But we don't need this! We only need to visit shutdown hook, when our master process stopped.
So we should check pid of current process in shutdown and allow shutdown only when it's same as was in startup.

### CODE REVIEW

**Comment by garex** [comment]
I'll rebase this and will send again.

**Comment by krakjoe** [comment]
I'm on it ...

**Comment by krakjoe** [comment]
Fixed in 1164fb2a5113503c43db49344e861a44974768b1

**Comment by garex** [comment]
Nice. 👍

**Pull request closed without merging**
